apiVersion: v1
kind: Service
metadata:
  name: daytrader
  labels:
    name: daytrader
spec:
  selector:
    name: daytrader
  ports:
  - name: https
    protocol: TCP
    port: 9443
    targetPort: 9443
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: daytrader
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: daytrader
    spec:
      containers:
      - name: daytrader
        image: daytrader:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9082
          - containerPort: 9443
        readinessProbe:
          httpGet:
            path: /
            port: 9082
        env:
        - name: MB_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mb-keystore-password
              key: password
        - name: MB_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mb-truststore-password
              key: password
        - name: dbUser
          valueFrom:
            secretKeyRef:
              name: db2-secret
              key: dbUser
        - name: dbPass
          valueFrom:
            secretKeyRef:
              name: db2-secret
              key: dbPass
        - name: tradeDbName
          value: trade
        - name: tradeDbHost
          value: db2-tradedb-0.db2-tradedb.default.svc.cluster.local
        - name: tradeDbPort
          value: "50000"
        - name: sessionDbName
          value: session
        - name: sessionDbHost
          value: db2-sessiondb-0.db2-sessiondb.default.svc.cluster.local
        - name: sessionDbPort
          value: "50000"
        - name: tranlogDbName
          value: tranlog
        - name: tranlogDbHost
          value: db2-tranlogdb-0.db2-tranlogdb.default.svc.cluster.local
        - name: tranlogDbPort
          value: "50000"
        volumeMounts:
          - name: keystores
            mountPath: /etc/wlp/config/keystore
            readOnly: true
          - name: truststores
            mountPath: /etc/wlp/config/truststore
            readOnly: true
          - name: liberty-config
            mountPath: /config/configDropins
      volumes:
        - name: keystores
          secret:
            secretName: mb-keystore
        - name: truststores
          secret:
            secretName: mb-truststore
        - name: liberty-config
          configMap:
            name: liberty-logging-config
            items:
              - key: keystore.xml
                path: defaults/keystore.xml
              - key: logging.xml
                path: defaults/logging.xml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: daytrader
  labels:
    name: daytrader
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/secure-backends: "true"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /
        backend:
          serviceName: daytrader
          servicePort: 9443
          