apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: db2
  name: argocd-role
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rolebinding
  namespace: db2
  annotations:
    argocd.argoproj.io/sync-wave: "3"
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: Role 
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: mysvcacct
  namespace: db2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
kind: Secret
apiVersion: v1
metadata:
  name: db-credential
  namespace: db2
data:
  dbpw: cGFzc3cwcmQ=
type: Opaque
