apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dt-pvclaim
  #namespace: oldt7-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
