apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: nest-ocp-dt7xa
  namespace: nest-ocp-dt7xa
spec:
  replicas: 1
  applicationImage: 'docker-na-public.artifactory.swg-devops.com/hyc-wassvt-team-image-registry-docker-local/svtapps/nest-daytrader7xa-otherapps-ol-http:latest'
  expose: true
  pullPolicy: Always
  #pullPolicy: IfNotPresent
  pullSecret: pull-secret
  route:
    host: nest-ocp-dt7xa-nest-ocp-dt7xa.apps.nest.cp.fyre.ibm.com
    path: /daytrader-xa
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  env:
    - name: DBHost
      value: 'nest-dt7xa-ocp-svl-db.fyre.ibm.com'
    - name: DBName
      value: TRADEDB
    - name: DBPort
      value: "50000"
    - name: DBUser
      value: db2inst1
    - name: DBPasswd
      valueFrom:
        secretKeyRef:
          name: db-credential
          key: dbpw
    - name: QueueManager
      value: QM1
    - name: mqHost
      value: 'nest-dt7xa-ocp-svl-mq.fyre.ibm.com'
    #- name: mqUser
    #  value: app
    #- name: mqPasswd
    #  valueFrom:
    #    secretKeyRef:
    #      name: mq-cred
    #      key: mqpw
    - name: traceString
      value: "daytrader=info"
    - name: httpPort
      value: "9080"
    - name: httpsPort
      value: "9443"
#  storage:
#    size: 64Gi
#    mountPath: "/logs"
#    volumeClaimTemplate:
#      metadata:
#        name: dt
#      spec:
#        accessModes: [ "ReadWriteMany" ]
#        storageClassName: 'rook-cephfs'
#        resources:
#          requests:
#            storage: 64Gi
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: dt-pvclaim
  volumeMounts:
    - name: shared-volume
      mountPath: "/shared-tranlogs"
  resourceConstraints:
    limits:
      cpu: 2000m
      memory: 2048Mi
    #requests:
    #  cpu:
    #  memory:
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50
  #monitoring:
  #  lables:
  #  endpoints:
